### ISSUE TITLE
运行x86版本后网易云音乐自动打开但是提示无法连接到网络，也听不了歌

### ISSUE THREAD

**Issue by yizhanchengyan** [maxkingmax/win10-Auto-deploy-nondanee-unblockneteasemusic#2]
之前用的代理也是，有一天突然就不行了。

**Comment by maxkingmax** [comment]
不要随便升级网易云音乐程序，目前好像只支持
![image](https://user-images.githubusercontent.com/26681826/184460466-8d44877b-4699-42d2-964d-f528ad1226e7.png)

[readme.md](https://github.com/maxkingmax/nondanee-unblock163music-helper#readme) 已经提供下载链接
