### ISSUE TITLE
还是不行呀

### ISSUE THREAD

**Issue by Liyooo** [maxkingmax/win10-Auto-deploy-nondanee-unblockneteasemusic#5]
是我使用姿势不对吗？还是不好使，灰色歌曲能点了，但是还是播放不了，VIP歌曲不显示VIP图标了，但也是不能播放

**Comment by maxkingmax** [comment]
首次 打开的《以父为名》能不能播放？

**Comment by maxkingmax** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月23日 14:01
收件人: ***@***.***>
抄送: ***@***.***>
主题: [maxkingmax/OnekeyUnlock163music] 还是不行呀 (Issue #5)


是我使用姿势不对吗？还是不好使，灰色歌曲能点了，但是还是播放不了，VIP歌曲不显示VIP图标了，但也是不能播放

―
这是我的目录结构，登录网易云音乐了？
***@***.***

**Comment by maxkingmax** [comment]
挂代理，再试试

**Comment by Liyooo** [comment]
可以了，谢谢！！
