### ISSUE TITLE
提个小请求

### ISSUE THREAD

**Issue by utrlman** [maxkingmax/win10-Auto-deploy-nondanee-unblockneteasemusic#6]
哥 你用了8080端口 我本地不好操作啊  我看你有ini配置文件 能否改成自定义端口？其他没什么问题能正常用 感谢老哥❥(^_-)

**Comment by maxkingmax** [comment]
已经弄好，更改为自定义端口后，需要手动调一下云音乐的代理端口。
https://github.com/maxkingmax/OnekeyUnlock163music/releases/tag/GUI_2.1

**Comment by maxkingmax** [comment]
已经弄好，更改为自定义端口后，需要手动调一下云音乐的代理端口。
https://github.com/maxkingmax/OnekeyUnlock163music/releases/tag/GUI_2.1
